import path from "node:path";
import { buildAllowKit } from "@zodiac-os/sdk/allow";
import { constellation as sdkConstellation } from "@zodiac-os/sdk";
import * as codegen from ".zodiac-os";
import { c as _c } from "zodiac-roles-sdk";
import type * as types from "./types";
import { ref as _ref } from "./ref";
import config from "../zodiac.config";

const abisDir = path.resolve(process.cwd(), config.abisDir ?? "abis");
const _allow = buildAllowKit(
  abisDir,
  config.contracts ?? {},
) as unknown as AllowKit;

// Pre-bind the local codegen so user code can call `constellation(opts)` without
// threading it through. Explicit is preferable to the SDK's default lazy
// `require('.zodiac-os')`, so the app fails fast at import if codegen is missing.
const _constellation = ((opts: any, internal?: any) =>
  sdkConstellation(opts, { codegen, ...internal })) as typeof sdkConstellation;

declare global {
  // `AllowKit` is augmented by `.zodiac-os/allow.d.ts` (regenerated by `bun pull-contracts`).
  var allow: AllowKit;
  var c: typeof _c;
  type Permissions = types.Permissions;
  type Specification = types.Specification;
  var ref: typeof _ref;
  var constellation: typeof sdkConstellation;
}

globalThis.allow = _allow;
globalThis.c = _c;
globalThis.ref = _ref;
globalThis.constellation = _constellation;
