import { allow as _allow } from "./allow";
import { c as _c } from "zodiac-roles-sdk";
import type * as types from "./types";
import { ref as _ref } from "./ref";

declare global {
  // `AllowKit` is declared by `.lib/generated/allow.d.ts` (regenerated by `bun run setup`).
  var allow: AllowKit;
  var c: typeof _c;
  type Permissions = types.Permissions;
  type Specification = types.Specification;
  var ref: typeof _ref;
}

globalThis.allow = _allow;
globalThis.c = _c;
globalThis.ref = _ref;
