import path from "node:path";
import { buildAllowKit } from "@zodiac-os/sdk/allow";
import { c as _c } from "zodiac-roles-sdk";
import type * as types from "./types";
import { ref as _ref } from "./ref";
import { constellation as _constellation } from "./constellation";
import contracts from "../contracts";

// Must match `abisDir` in zodiac.config.ts. Kept separate to avoid pulling
// the config's apiKey check (which reads env) into the runtime path.
const abisDir = path.resolve(process.cwd(), "abis");
const _allow = buildAllowKit(abisDir, contracts) as unknown as AllowKit;

declare global {
  // `AllowKit` is augmented by `.zodiac-os/allow.d.ts` (regenerated by `bun pull-contracts`).
  var allow: AllowKit;
  var c: typeof _c;
  type Permissions = types.Permissions;
  type Specification = types.Specification;
  var ref: typeof _ref;
  var constellation: typeof _constellation;
}

globalThis.allow = _allow;
globalThis.c = _c;
globalThis.ref = _ref;
globalThis.constellation = _constellation;
